import '@/assets/svg/loading.svg';
import '@/assets/svg/all.svg';
import '@/assets/svg/cart.svg';
import '@/assets/svg/back.svg';
import '@/assets/svg/category.svg';
import '@/assets/svg/comments.svg';
import '@/assets/svg/search.svg';
import '@/assets/svg/set.svg';
import '@/assets/svg/refresh.svg';
